# Generated by Django 6.0.3 on 2026-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
